-- MySQL Script generated by MySQL Workbench
-- Thu Sep  1 19:50:33 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedores` (
  `idproveedores` INT NOT NULL AUTO_INCREMENT,
  `proveedoresrep` VARCHAR(45) NOT NULL,
  `proveedoresnombre` VARCHAR(45) NOT NULL,
  `proveedorestel1` INT NOT NULL,
  `proveedorescontacto1` VARCHAR(45) NOT NULL,
  `proveedorestel2` INT NOT NULL,
  `proveedorescontacto2` VARCHAR(45) NOT NULL,
  `proveedorescat` VARCHAR(45) NOT NULL,
  `proveedoresmail` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproveedores`),
  UNIQUE INDEX `idproveedores_UNIQUE` (`idproveedores` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `idclientes` INT NOT NULL AUTO_INCREMENT,
  `clientesnombre` VARCHAR(45) NOT NULL,
  `clientesapellido` VARCHAR(45) NOT NULL,
  `clientesdir` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idclientes`),
  UNIQUE INDEX `idclientes_UNIQUE` (`idclientes` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `productosnombre` VARCHAR(45) NOT NULL,
  `productosprecio` INT NOT NULL,
  `productoscat` VARCHAR(45) NOT NULL,
  `productosprov` INT NOT NULL,
  `productoscolor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproductos`),
  UNIQUE INDEX `idproductos_UNIQUE` (`idproductos` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ventas` (
  `idventas` INT NOT NULL AUTO_INCREMENT,
  `ventasidclientes` INT NOT NULL,
  `ventasidproducto` INT NOT NULL,
  `ventasidproveedores` INT NOT NULL,
  PRIMARY KEY (`idventas`),
  UNIQUE INDEX `idventas_UNIQUE` (`idventas` ASC) VISIBLE,
  INDEX `ventasidproducto_idx` (`ventasidproducto` ASC) VISIBLE,
  INDEX `ventasidclientes_idx` (`ventasidclientes` ASC) VISIBLE,
  INDEX `ventasidproveedores_idx` (`ventasidproveedores` ASC) VISIBLE,
  CONSTRAINT `ventasidclientes`
    FOREIGN KEY (`ventasidclientes`)
    REFERENCES `mydb`.`clientes` (`idclientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ventasidproducto`
    FOREIGN KEY (`ventasidproducto`)
    REFERENCES `mydb`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ventasidproveedores`
    FOREIGN KEY (`ventasidproveedores`)
    REFERENCES `mydb`.`proveedores` (`idproveedores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- Utilizar la base de datos creada para TeLoVendo
USE mydb;

-- Ingresar 5 proveedores
INSERT INTO proveedores (idproveedores, proveedoresrep, proveedoresnombre, proveedorestel1, proveedorescontacto1, proveedorestel2, proveedorescontacto2, proveedorescat, proveedoresmail) VALUES (1, "Juan Perez", "Supertecno", 987456327, "Alberto Fernandez", 942567386, "Margarita Rita", "Insumos electronicos", "supertecno@supertecno.cl");
INSERT INTO proveedores (idproveedores, proveedoresrep, proveedoresnombre, proveedorestel1, proveedorescontacto1, proveedorestel2, proveedorescontacto2, proveedorescat, proveedoresmail) VALUES (2, "Pedro Pulido", "Tecnosolution", 982114366, "Francisco Aldanez", 988556417, "Emilio Paredes", "Insumos electronicos", "tecnosolution@tecnosolution.cl");
INSERT INTO proveedores (idproveedores, proveedoresrep, proveedoresnombre, proveedorestel1, proveedorescontacto1, proveedorestel2, proveedorescontacto2, proveedorescat, proveedoresmail) VALUES (3, "Maria Iniesta", "Frikitecno", 944326519, "Silvia Hernandez", 998744563, "Andres Bustamante", "Accesorios no electronicos", "frikitecno@frikitecno.cl");
INSERT INTO proveedores (idproveedores, proveedoresrep, proveedoresnombre, proveedorestel1, proveedorescontacto1, proveedorestel2, proveedorescontacto2, proveedorescat, proveedoresmail) VALUES (4, "Matias Carmona", "Gamertec", 978865567, "Manuel Burgos", 923657345, "Cristina Font", "Insumos electronicos", "gamertec@gamertec.cl");
INSERT INTO proveedores (idproveedores, proveedoresrep, proveedoresnombre, proveedorestel1, proveedorescontacto1, proveedorestel2, proveedorescontacto2, proveedorescat, proveedoresmail) VALUES (5, "Gonzalo Prado", "Microtec", 923541642, "Marcos Prat", 932425687, "Nicole Pizarro", "Insumos electronicos", "microtec@microtec.cl");
-- Ingresar 5 clientes
INSERT INTO clientes (idclientes, clientesnombre, clientesapellido, clientesdir) VALUES (1, "Sergio", "Echaurren", "Avenida Alemania 234");
INSERT INTO clientes (idclientes, clientesnombre, clientesapellido, clientesdir) VALUES (2, "Magdalena", "Pedrosa", "Calle del Agua 201");
INSERT INTO clientes (idclientes, clientesnombre, clientesapellido, clientesdir) VALUES (3, "Arturo", "Segura", "Pasaje Prat 40");
INSERT INTO clientes (idclientes, clientesnombre, clientesapellido, clientesdir) VALUES (4, "Josefina", "Errazuriz", "Calle del Mar 33");
INSERT INTO clientes (idclientes, clientesnombre, clientesapellido, clientesdir) VALUES (5, "Esteban", "Coestaocupado", "Avenida Platano 88");
-- Ingresar 10 productos (Como cada producto puede tener varios proveedores y varios colores, se agregan esos campos, pero pueden estar vacios)
ALTER TABLE productos ADD productosprov2 INT;
ALTER TABLE productos ADD productosprov3 INT;
ALTER TABLE productos ADD productosprov4 INT;
ALTER TABLE productos ADD color2 VARCHAR (45);
ALTER TABLE productos ADD color3 VARCHAR (45);
ALTER TABLE productos ADD color4 VARCHAR (45);
INSERT INTO productos (idproductos, productosnombre, productosprecio, productoscat, productosprov, productoscolor) VALUES (1, "mouse hp 888", 5000, "accesorios computacion", 1, "negro");
INSERT INTO productos (idproductos, productosnombre, productosprecio, productoscat, productosprov, productoscolor, productosprov2, productosprov3, productosprov4, color2, color3, color4) VALUES (2, "mouse lenovo 799", 6000, "accesorios computacion", 1, "negro", 5, NULL, NULL, "rojo", "", "");
INSERT INTO productos (idproductos, productosnombre, productosprecio, productoscat, productosprov, productoscolor, productosprov2, productosprov3, productosprov4, color2, color3, color4) VALUES (3, "pantalla microsoft 34", 120000, "accesorios computacion", 2, "unico", 1, NULL, NULL, "", "", "");
INSERT INTO productos (idproductos, productosnombre, productosprecio, productoscat, productosprov, productoscolor, productosprov2, productosprov3, productosprov4, color2, color3, color4) VALUES (4, "pantalla samsung 222", 80000, "accesorios computacion", 4, "negro", 2, NULL, NULL, "rojo", "", "");
INSERT INTO productos (idproductos, productosnombre, productosprecio, productoscat, productosprov, productoscolor, productosprov2, productosprov3, productosprov4, color2, color3, color4) VALUES (5, "notebook lenovo 790", 700000, "notebooks", 1, "negro", 2, 4, 5, "rojo", "azul", "gris");
INSERT INTO productos (idproductos, productosnombre, productosprecio, productoscat, productosprov, productoscolor, productosprov2, productosprov3, productosprov4, color2, color3, color4) VALUES (6, "mousepad jonsnow", 5000, "accesorios", 3, "unico", NULL, NULL, NULL, "", "", "");
INSERT INTO productos (idproductos, productosnombre, productosprecio, productoscat, productosprov, productoscolor, productosprov2, productosprov3, productosprov4, color2, color3, color4) VALUES (7, "impresora hp 5000", 30000, "accesorios computacion", 1, "blanco", 4, NULL, NULL, "gris", "", "");
INSERT INTO productos (idproductos, productosnombre, productosprecio, productoscat, productosprov, productoscolor, productosprov2, productosprov3, productosprov4, color2, color3, color4) VALUES (8, "impresora hp 9000", 45000, "accesorios computacion", 1, "blanco", 5, NULL, NULL, "azul", "", "");
INSERT INTO productos (idproductos, productosnombre, productosprecio, productoscat, productosprov, productoscolor, productosprov2, productosprov3, productosprov4, color2, color3, color4) VALUES (9, "notebook hp h500", 860000, "notebooks", 1, "negro", 5, 4, NULL, "rojo", "azul", "");
INSERT INTO productos (idproductos, productosnombre, productosprecio, productoscat, productosprov, productoscolor, productosprov2, productosprov3, productosprov4, color2, color3, color4) VALUES (10, "mousepad sailormoon", 5000, "accesorios", 3, "unico", NULL, NULL, NULL, "", "", "");
-- Cada producto puede tener más de un proveedor así que cada columna de proveedores está referenciada con la tabla proveedores y la idproveedores
ALTER TABLE productos ADD CONSTRAINT `productosprov2`
    FOREIGN KEY (`productosprov2`)
    REFERENCES `mydb`.`proveedores` (`idproveedores`);
ALTER TABLE productos ADD CONSTRAINT `productosprov3`
    FOREIGN KEY (`productosprov3`)
    REFERENCES `mydb`.`proveedores` (`idproveedores`);
ALTER TABLE productos ADD CONSTRAINT `productosprov4`
    FOREIGN KEY (`productosprov4`)
    REFERENCES `mydb`.`proveedores` (`idproveedores`);

-- Para saber la categoría que más se repite:
select productoscat, count(productoscat) maximo
from
productos
group by
productoscat having count(productoscat) =
(select
max(i.total) from
(select count(productoscat) as total
from productos
group by productoscat) i);

-- Para saber cuales son los productos con mayor stock
-- La columna stock no había sido creada así que se debe crear y agregarle valores.
ALTER TABLE productos ADD stock INT NOT NULL;
UPDATE productos 
SET stock='6'
WHERE idproductos='1';
UPDATE productos 
SET stock='20'
WHERE idproductos='2';
UPDATE productos 
SET stock='7'
WHERE idproductos='3';
UPDATE productos 
SET stock='99'
WHERE idproductos='4';
UPDATE productos 
SET stock='96'
WHERE idproductos='5';
UPDATE productos 
SET stock='67'
WHERE idproductos='6';
UPDATE productos 
SET stock='33'
WHERE idproductos='7';
UPDATE productos 
SET stock='45'
WHERE idproductos='8';
UPDATE productos 
SET stock='101'
WHERE idproductos='9';
UPDATE productos 
SET stock='80'
WHERE idproductos='10';

-- Cuáles son los productos con mayor stock

SELECT productosnombre, MAX(stock)
FROM productos
GROUP BY productosnombre


-- Para saber qué color de producto es el más común
SELECT productoscolor, count(*)
FROM productos
GROUP BY productoscolor
HAVING COUNT(*)>1;

SELECT color2, count(*)
FROM productos
GROUP BY color2
HAVING COUNT(*)>1;

SELECT color3, count(*)
FROM productos
GROUP BY color3
HAVING COUNT(*)>1 ;

SELECT color4, count(*)
FROM productos
GROUP BY color4
HAVING COUNT(*)>1;


-- Cual o cuales son los proveedores con menor stock de productos.

SELECT productosnombre,MIN(stock)
FROM productos
GROUP BY productosnombre

-- Cambien la categoría de productos más popular por ‘Electrónica y computación’.


